# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'QiscusCore', :path => '../../'
  pod 'QiscusRealtime', :git => 'https://github.com/qiscus/QiscusRealtime-iOS.git', :branch => 'carthage-support'

end
